version: '3.9'

services:
  server:
    image: node:16
    volumes:
      - ./server:/code
    working_dir: /code
    command: npm start
    ports:
      - '8000:8000'
  mongodb:
    ports:
      - '27017:27017'
  caddy:
    image: caddy:2.6.4
    container_name: hhahaiti_caddy
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./client/build:/var/www/
    environment:
      - DOMAIN=localhost
      - API_HOSTNAME=hhahaiti_server
    ports:
      - '8080:80'
      - '8443:443'
      - '2019:2019'
