version: "3.9"

services:
  server:
    container_name: hhahaiti_server
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVER_PORT=5000
  mongodb:
    container_name: hhahaiti_mongodb
    image: mongo:5.0.6-focal
    volumes:
      - hhahaiti_mongodb_data:/data/db

volumes:
  hhahaiti_mongodb_data: