version: '3.9'

services:
  server:
    image: node:16
    volumes:
      - ./server:/code
    working_dir: /code
    command: npm start
    ports:
      - '8000:8000'
  mongodb:
    ports:
      - '27017:27017'
  caddy:
    image: caddy:2.6.4
    container_name: hhahaiti_caddy
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile_local:/etc/caddy/Caddyfile
      # - ./client/build:/var/www/
    environment:
      - DOMAIN=myapp.local
      - API_HOSTNAME=hhahaiti_server
    ports:
      - '3000:80'
      - '3443:443'
      - '2019:2019'
  grafana:
    image: grafana/grafana-enterprise
    container_name: hha_grafana
    restart: unless-stopped
    ports:
     - '8443:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
     - GF_SERVER_ROOT_URL=http://localhost:3000/
     - GF_INSTALL_PLUGINS=grafana-clock-panel

volumes:
  grafana_data:
