version: '3.9'

services:
  server:
    container_name: hhahaiti_server
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVER_PORT=8000
  mongodb:
    container_name: hhahaiti_mongodb
    image: mongo:5.0.6-focal
    volumes:
      - hhahaiti_mongodb_data:/data/db
  log_metrics_processor:
    container_name: hhahaiti_fluentbit
    image: fluent/fluent-bit:2.0.11
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./fluentbit-config:/fluent-bit/etc
    logging:
      driver: "none"
  prometheus:
    image: prom/prometheus:latest
    container_name: hhahaiti_prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - hhahaiti_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    # networks:
    #   - monitoring
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    # networks:
    #   - monitoring
  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: hhahaiti_mongodb_exporter
    restart: unless-stopped
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    


volumes:
  hhahaiti_mongodb_data:
  hhahaiti_prometheus_data: {}

# networks:
#   monitoring:
#     driver: bridge