version: '3.7'

services:
  server:
    network_mode: host
    build:
      context: ./server
      dockerfile: Dockerfile
    image: hha-app-server
    container_name: hha-app-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
  mongodb:
    network_mode: host
    container_name: hha-app-mongo
    image: mongo
    volumes:
      - db:/data/db
  client:
    network_mode: host
    build:
      context: ./client
      dockerfile: Dockerfile
    image: hha-app-client
    container_name: hha-app-client
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    stdin_open: true # docker run -i
    tty: true # docker run -t

volumes:
  db:
    driver: local
