version: '3.9'

services:
  server:
    container_name: hhahaiti_server
    depends_on:
      - mongodb
      - logger
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVER_PORT=8000
    volumes:
      - server_logs:/var/log
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}.{{.ID}}
        fluentd_async: true
        fluentd-address: tcp://localhost:24224

  mongodb:
    container_name: hhahaiti_mongodb
    depends_on:
      - logger
    image: mongo:5.0.6-focal
    volumes:
      - hhahaiti_mongodb_data:/data/db
      - mongo_logs:/var/log
    logging:
      driver: fluentd

volumes:
  hhahaiti_mongodb_data:
  fluentbit_logs_db:
  fluentbit_logs_output:
  mongo_logs:
  server_logs:
