export const MESSAGE_ADDED_SUCCESSFULLY: string = 'Message is successfully added!';
export const MESSAGE_DELETED_SUCCESSFULLY: string = 'Message deleted!';
export const MESSAGE_NO_DEPARTMENT_SELECTED: string = 'Must select a department';
export const MESSAGE_ERROR: string = 'Internal Error: Unable to add message';
export const BIO_MECH_ADDED_SUCCESSFULLY: string = 'Report successfully created!';
export const BIO_MECH_DELETED_SUCCESSFULLY: string = 'Report successfully deleted!';
export const EOTM_UPDATED_SUCCESSFULLY: string = 'Employee of the month successfully updated!';
export const EOTM_CREATED_SUCCESSFULLY: string = 'Employee of the month successfully created!';
export const MISSING_TITLE_BODY_MSG: string = 'Must provide the title and body';
