name: Mirror Repo
# Mirror the project to GitHub.com
on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  mirror-to-githubcom:
    runs-on: [self-hosted, docker]
    container:
      image: node:18
    steps:
      - uses: bfraser/cicd/actions/mirror_to_github@v1
        with:
          target_github_user:  ${{ secrets.MIRROR_TO_GITHUB_USER }}
          target_github_token: ${{ secrets.MIRROR_TO_GITHUB_TOKEN }}
          # Where to mirror to; likely format is:
          #    github.com/<user>/<repo>.git
          target_github_url:   ${{ secrets.MIRROR_TO_GITHUB_URL }}
          source_github_token: ${{ secrets.GITHUB_TOKEN }}
